services:
  database:
    image: 'postgres:16.11-alpine3.23' #vers√£o do banco
    environment: # Variaveis de ambiente do banco
      POSTGRES_PASSWORD: 'local_password'
    ports:
      - "5432:5432"
